### ISSUE TITLE
Yasnippet-global-mode seems to break python-shell-send-buffer

### ISSUE THREAD

**Issue by harritaylor** [joaotavora/yasnippet#1043]
Hey, when I have yasnippet's global-mode enabled, it seems to break C-c C-c in a python-mode buffer. I get the following error:
```
run-hooks: Symbol’s function definition is void: yasnippet-snippets--fixed-indent
```
It doesn't break when I have a per-buffer minor mode, but the minor mode seems to not actually expand snippets. Not sure what I'm doing wrong or if this is a bug. Thanks!

**Comment by harritaylor** [comment]
Found the culprit! It was a line in AndreaCrotti's templates.

**Comment by mok0** [comment]
OP, I had the same problem, but I don't want to install `yasnippet-snippets` with `use-package` because I have made a lot of changes in the macros, and I only need yas in a handful of the modes.

I found that the problem is that there was an outdated version of a hidden file `snippets/python/.yas-setup.el` where the function `yasnippet-snippets--fixed-indent` was called. I replaced this file with the same from the github repo and the problem went away. I think it's very poor practice to put executable code in a hidden `.el`  file, there must be another way to distinguish it from a macro.
