### ISSUE TITLE
[Feature] Support tree-sitter

### ISSUE THREAD

**Issue by seagle0128** [joaotavora/yasnippet#1157]
I am always enjoying this great package. Thanks a lot!

Recently Emacs 29 introduces native `tree-sitter`, and I read this interesting post: https://xenodium.com/emacs-generate-a-swift-initializer/ .

IMO, **Context-aware yasnippets** is amazing feature. I am not sure if it could be implemented in `yasnippet`, but please think about this idea. Thanks!

**Comment by Cons-Cat** [comment]
Another interesting example can be seen here: https://blog.meain.io/2021/intelligent-snippets-treesitter/

**Comment by monnier** [comment]
Fancier snippets that make use of the richer syntax information provided by tree-sitter sound great.  But these belong with the [yasnippet-snippets](http://elpa.nongnu.org/nongnu/yasnippet-snippets.html) rather than here, unless they require special support from YASnippet itself.
So I'm closing this for now.  Feel free to open a new issue if/when you find that such snippets indeed require special extra support from YASnippet.
