### ISSUE TITLE
term, ansi-term: error when pressing tab to autocomplete

### ISSUE THREAD

**Issue by benma** [joaotavora/yasnippet#289]
Hi there

When yas/minor-mode is activated in a term/ansi-term buffer, pressing tab results in the following error:

`term-send-raw: Wrong type argument: characterp, tab`.

This is new behavior, introduced by one of the changes in the last couple of weeks. It only occurs when emacs is runs in a window. In the console, everything is working.

As a workaround, I included this in my .emacs:

``` lisp
(add-hook 'term-mode-hook (lambda()
                (yas-minor-mode -1)))
```

I know of `yas--dont-activate` but I haven't figured out yet how to use it. 

Knowing the code base better, maybe you know right off the bat what might be causing the problem. Otherwise, I will dig into it sometime.

**Comment by PythonNut** [comment]
Just wanted to say that `yasnippet` still breaks the term modes in an `emacs -Q`.

**Comment by tdavis** [comment]
In the intervening years I bit the bullet and threw away the term modes in favour of eshell.

**Comment by capitaomorte** [comment]
@tdavis you could have also
```
(add-hook 'term-mode-hook (lambda () (yas-minor-mode -1)))
```

**Comment by tdavis** [comment]
@capitaomorte Oh, sure. Unfortunately, yasnippet being busted is far from the only quirk of the term modes. And with a tiling wm I'm a quick key combo away from an actual terminal fitted below whatever Emacs frame I'm in.

**Comment by capitaomorte** [comment]
Yeah shell-in-emacs solutions were never extremely good, and it's good to be worth something outside emacs, too. Tiling wm's rock, in linux I use stumpwm, wish I could use it in mac osx.

**Comment by npostavs** [comment]
I looked at the code, the problem is `yas--keybinding-beyond-yasnippet` searches under the translated `TAB` key when it doesn't find a binding for `<tab>`, but it doesn't change `this-command-keys` internal variable to `TAB` (it's not writable from lisp).

I thought the `keys` argument to `call-interactively` would help, but... it doesn't. So this appears unfixable, but another workaround is `(define-key yas-minor-mode-map [tab] nil)` i.e. remove the `<tab>` binding for `yas-expand`, leaving only the `TAB` binding.

**Comment by capitaomorte** [comment]
@npostavs, that might help, might I'm also afraid it'll break snippet expansion in emacsen without a window-system, at least that's what I remember `<tab>` being there for.   

I've juu=st checked now, and it seems to work without it, so I wonder why. 

According to the comments it's:

```
;; Apropos the trigger key and the fallback binding:
;;
;; When `yas-minor-mode-map' binds <tab>, that correctly overrides
;; org-mode's <tab>, for example and searching for fallbacks correctly
;; returns `org-cycle'. However, most other modes bind "TAB". TODO,
;; improve this explanation.
;;
```

So if we `(define-key yas-minor-mode-map [tab] nil)` we'll get a lot of org-mode bitching. Unless we can convince org-mode to use TAB, too. Or put our hook into `org-mode-hook`. But that's no good, too.

I can take a look at `yas--keybinding-beyond-yasnippet` again, otherwise I'd rather leave this unsolved with your workaround @npostavs

**Comment by npostavs** [comment]
> that might help, might I'm also afraid it'll break snippet expansion in emacsen without a window-system

Without a window-system Emacs always gets `TAB` and never `<tab>`, I think. So `<tab>` bindings should be irrelevant in this case.

With a window-system bindings of `<tab>` (e.g. from org-mode) take precedence over `TAB` bindings, so yeah, it's not really a practical fix.

**Comment by fud** [comment]
I'm still getting this in 2016 but turned it off via @benma instructions.

**Comment by tsdeng** [comment]
getting this from 2016...

**Comment by ninrod** [comment]
just to add that I'm also getting screwed by this.

**Comment by joaotavora** [comment]
@npostavs we could add this workaround to `yasnippet.el` by default, meaning yasnippet could add some `yas--turn-off-tab-trigger` to some major mode's hooks, including `term-mode`

**Comment by npostavs** [comment]
I think we can fix things by using the `(menu-item ... :filter...)` trick instead, see http://stackoverflow.com/a/22863701/319698. And this will probably simplify things a lot too.

**Comment by joaotavora** [comment]
> And this will probably simplify things a lot too

yeah, it's the way to go...go for it!

**Comment by npostavs** [comment]
Initial patch in #760
