### ISSUE TITLE
Eating spaces when mirrors appear at the beginning of a line

### ISSUE THREAD

**Issue by 19000** [joaotavora/yasnippet#712]
I found when mirrors, `$1` for example, appear in the beginning of a line and surrounded with spaces, the leading and trailing spaces of the mirror do not follow the format of snippet file exactly, especially when there are multiple mirrors in the same line (like this: `$1   ---------------- $1 ----`).
Feel like it trims the leading spaces and the mirror token `$1` altogether, then indents the whole line follow certain rule.

Already tried `# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))`, and it only works when mirrors are not in the beginning of a line.

How could I retain all my spaces, just insert fields into mirrors? Any `expand-env` out there for this case?

--------
Environment info for reference:
- Emacs version: GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-08-25
- Yasnippet version: yasnippet (version 0.10.0) -- pluskid/joaotavora/npostavs

```
emacs -Q

(add-to-list 'load-path "~/.emacs.d/plugins/yasnippet")
(require 'yasnippet)
(yas-global-mode 1)
```
--------
Below is my `text-mode` snippet file, followed by desired and actual output expanded in `test.txt`.

This snippet has `$1` in the beginning of a line, and multiple `$1` in one line.
```
# -*- mode: snippet -*-
# name: mytest-yas
# key: mytest
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))
# --
${1:XXXXX} --------
$1   ---------------- $1 ----
$1   ------------------------

```
What I expect:
```
XXXXX --------
XXXXX   ---------------- XXXXX ----
XXXXX   ------------------------
```

What actual expanded in file `test.txt` when `yas-expand`. (Spaces after the first `XXXXX`  disappeared in line 2. And the leading spaces added in line 3 are unexpected.)
```
XXXXX --------
XXXXX---------------- XXXXX ----
   XXXXX   ------------------------


```

Typed `UUU` in field 1, the leading spaces in line 3 disappeared.
```
UUU --------
UUU---------------- UUU ----
UUU   ------------------------


```

-------------
A more sophisticated test case with more mirrors and leading spaces.
```
# -*- mode: snippet -*-
# name: mytest-yas
# key: mytest
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))
# --
${1:XXXXX} --------
$1 ---------------- $1 ---- with multi mirrors and leading space
$1 ------------------------ with leading space after mirror
           $1 ------------- with leading space before & after mirror
   $1
        -----------
                -------- $1 ------ $1
        -------- $1 ------ $1
        -------------- $1
        ------ with trailing spaces                          
        ------ with trailing spaces $1          
------------
        $0
```

In file `test.txt`, it expands like this, and it's mixed with spaces and tabs, while tabs are not written in the snippet above.
```
XXXXX --------
XXXXX---------------- XXXXX ---- with multi mirrors and leading space
 XXXXX ------------------------ with leading space after mirror
 XXXXX ------------- with leading space before & after mirror
	    XXXXX
        -----------
        -------- XXXXX ------ XXXXX
		-------- XXXXX ------ XXXXX
        -------------- XXXXX
        ------ with trailing spaces                          
        ------ with trailing spaces XXXXX          
------------
        

```
Type `U` three times, it becomes:
```
UUU --------
UUU---------------- UUU ---- with multi mirrors and leading space
UUU ------------------------ with leading space after mirror
UUU ------------- with leading space before & after mirror
UUU
        -----------
        -------- UUU ------ UUU
	-------- UUU ------ UUU
	-------------- UUU
        ------ with trailing spaces                          
        ------ with trailing spaces UUU          
------------
        

```

**Comment by 19000** [comment]
Actually, I find this issue when I write a c-mode snippet:
```
# -*- mode: snippet -*-
# name: mytest-yas
# key: mytest
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))
# --
${1:struct ${2:TreeNode}} *constructBinaryTreeFromList(int *arr, int len);
$1 *constructBinaryTreeFromList_Helper(int *arr, int len, $1 ***nodePList);
```

But, shown as below, a space was lost between `TreeNode` and `*constructBinaryTreeFromList_Helper` in the 2nd line:
```
struct TreeNode *constructBinaryTreeFromList(int *arr, int len);
struct TreeNode*constructBinaryTreeFromList_Helper(int *arr, int len, struct TreeNode ***nodePList);
```

This case doesn't happen in lines contain only 1 mirror. (You can highlight it by search `$1`)

**Comment by npostavs** [comment]
Thanks for the detailed report. The problem seems to be that `yas--mirror-update-display` does indentation of the lines where the mirror is on after updating it (this was done for #665). I think the solution is not to avoid indenting the first line of the mirror (which means no indentation would be done for single line mirrors).

**Comment by 19000** [comment]
Updated and it works now.
Thanks!

**Comment by joaotavora** [comment]
> The problem seems to be that yas--mirror-update-display does indentation of the lines where the mirror is on after updating it

I don't understand. Do you mean "does indentation [...] before updating [the mirror]?". Because that's the only way I can see a space disappearing in the middle of the line.

The problem rather seems to be when there are *two* mirrors of a field on the same line: while taking care of a mirror that happens in the middle of the line, the other one at the front of the line is usually unprotected. Calling `yas--indent-region` on the middle mirror destroys the precious leading whitespace because the front mirror isn't showing any reflection yet.

I see three solutions:

1. Sort the mirrors to be updated by starting position.
2. Have `yas-indent-region` skip the first line iff there is there is non-whitespace text before its `from` argument.
3. Don't actually indent in `yas--mirror-update-display`, but push a region for later indenting and decide later.

Number 1 seems easiest and correct enough. I've implemented it in d218ed8b1bf95809edc148e609c59b124598695d which I think you should consider cherry-picking (perhaps after some more tests?). Number 2 wouldn't be bad either.

> I think the solution is not to avoid indenting the first line of the mirror (which means no indentation would be done for single line mirrors).

This probably works: after all, indenting mirrors but it's the worst solution in my opinion and would destroy a reasonably nice benefit of eca2f995c15dda7632701f7cb682643f6c9597b6, which is that single line mirrors (particularly those one a single empty line) enjoy safer indenting.

**Comment by npostavs** [comment]
> I don't understand. Do you mean "does indentation [...] before updating [the mirror]?". Because that's the only way I can see a space disappearing in the middle of the line.
> 
> The problem rather seems to be when there are two mirrors of a field on the same line

The problem of wrong indentation can happen with only one mirror per line:

```
# -*- mode: snippet -*-
# name: mytest-yas
# key: mytest
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))
# --
${1:XXXXX} --------
$1   ------------------------
$1   ------------------------
```

gives
```
XXXXX --------
XXXXX   ------------------------
   XXXXX   ------------------------
```

But the sorting solution covers that too.

> I've implemented it in d218ed8 which I think you should consider cherry-picking (perhaps after some more tests?). Number 2 wouldn't be bad either.

Number 2 seems too hacky to me. I think 3 might be best, but since you've already implemented 1 and it works, I will probably just use it.

> a reasonably nice benefit of eca2f99, which is that single line mirrors (particularly those one a single empty line) enjoy safer indenting.

Can you show a concrete example where this makes a difference? I'm having trouble coming up with one.

**Comment by joaotavora** [comment]
> The problem of wrong indentation can happen with only one mirror per line:

In that case then it is probably `yas--indent-region` that is doing something funny, like indenting lines outside the ones requested by the `from` and `to` arguments passed to it. 

> But the sorting solution covers that too.

Great. Funny though, I'll check tomorrow.

> Number 2 seems too hacky to me. 

Doesn't seem so hacky to me: it's a resonable contract to expect from an indenting function that, when mandated to indent a region, it doesn't touch any characters outside that region. It's probably not what Emacs's `indent-region` does, though, so I can probably see your point.

> Can you show a concrete example where this makes a difference? I'm having trouble coming up with one.

It allows user's to be more lazy. In ruby, this now becomes indented correctly right?

```
def $1
$1
end
```

Also, some more contorted stuff
```
def bla ($1,$2,$3)
$1
$2
$3
end
```
If the user uses `begin` for `$1` and `end` for `$3`, `$2` should be indented to 4 spaces, right? This example is silly but some context-aware indentation length scenario where the context is partly also a mirror is not unthinkable.

**Comment by npostavs** [comment]
> In that case then it is probably `yas--indent-region` that is doing something funny, like indenting lines outside the ones requested by the from and to arguments passed to it.

No, it's just that in this scenario (before the 1st mirror has been filled in)
```
XXXXX --------
   ------------------------
XXXXX   ------------------------
```
Indenting the 3rd line will add spaces. When we do the mirrors in order, this problem is avoided.

> Doesn't seem so hacky to me: it's a resonable contract to expect from an indenting function that, when mandated to indent a region, it doesn't touch any characters outside that region. It's probably not what Emacs's `indent-region` does, though, so I can probably see your point.

Oh right, I'm so used to `indent-region` behaviour I didn't think of that.

> It allows user's to be more lazy. In ruby, this now becomes indented correctly right?

Thanks, I added this as an additional test, so we can be sure not to lose this behaviour again. 9c9952c19a1ed4c28e303a9903f77d9b998876e3

---

> since you've already implemented 1 and it works, I will probably just use it.

I merged your code (plus the added test) 8ca8c7de4f0f898d4f29af800b83f5e8d79d9a66.

**Comment by joaotavora** [comment]
> Indenting the 3rd line will add spaces. When we do the mirrors in order, this problem is avoided.

Oh I see, yes so then it makes sense. It's actually an example of indentation aware of other context other than the current line.

> Thanks, I added this as an additional test, so we can be sure not to lose this behaviour again. 9c9952c

Great idea

**Comment by broncodev** [comment]
My really nice bug report was deleted by a silly C-w (which means something different in Emacs than in my browser)

When I create a new buffer in c-mode, I get this:
[yas] Committing snippets. Action would destroy a protection overlay.

My configuration:
(running emacs -Q)
emacs GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2)
yasnippet 20170203.626
.emacs (init file)
(require 'package)
(package-initialize)
(require 'yasnippet)
(define-key yas-minor-mode-map (kbd "<tab>") nil)
(define-key yas-minor-mode-map (kbd "TAB") nil)
(define-key yas-minor-mode-map (kbd "C-i") nil)
(define-key yas-minor-mode-map (kbd "C-S-i") 'yas-expand)

(add-hook 'prog-mode-hook 'yas-minor-mode)

(require 'function-args)
(add-hook 'c-mode-common-hook (lambda ()
                                (function-args-mode) ; Find definitions in current buffer
                                (setq tab-width 4) ; set tab width to 4
                                (auto-fill-mode) ; break long lines
                                (yas-minor-mode) ; activate yasnippet
                                ))

I found this, which could be related.
https://github.com/joaotavora/yasnippet/issues/537

Thanks!

**Comment by npostavs** [comment]
> My really nice bug report was deleted by a silly C-w (which means something different in Emacs than in my browser)

I've done that before too. :/

> I found this, which could be related.
> #537

This issue is not though, so please [open a new one](https://github.com/joaotavora/yasnippet/issues/new).
