### ISSUE TITLE
Hook `yas-exterminate-package' into `unload-feature'

### ISSUE THREAD

**Issue by spwhitton** [joaotavora/yasnippet#753]
Dear maintainer,

A Debian user suggests hooking `yas-exterminate-package` into `unload-feature`.  This can be done by defining `yasnippet-unload-feature`, a function that would call `yas-exterminate-package`.  Please see [their feature request](https://bugs.debian.org/674240).

Thanks.

**Comment by npostavs** [comment]
Hmm, `yas-exterminate-package` doesn't exist anymore. I'm not sure what it did.

**Comment by spwhitton** [comment]
On Mon, Nov 28, 2016 at 05:33:00AM -0800, Noam Postavsky wrote:
> Hmm, yas-exterminate-package doesn't exist anymore. I'm not sure what it did.

It's in yasnippet-debug.el.

-- 
Sean Whitton

**Comment by npostavs** [comment]
> It's in yasnippet-debug.el.

Oh, so it is.
```elisp
(defun yas-exterminate-package ()
  (interactive)
  (yas-global-mode -1)
  (yas-minor-mode -1)
  (mapatoms #'(lambda (atom)
                (when (string-match "yas[-/]" (symbol-name atom))
                  (unintern atom obarray)))))
```

I think `unload-feature` already covers turning off the modes, and, as noted in the Debian bug report, uninterning is probably not a good idea anyway. So this function could probably just be dropped (it's effectively already dropped by hiding it it in yasnippet-debug.el).

Currently `unload-feature` doesn't work when using the default snippet repo though, because it contains a .yas-setup.el file which does `(require 'yasnippet)`. And even without that, it looks like `unload-feature` gets confused by `cl-defstruct`.

**Comment by spwhitton** [comment]
Hmm.  So without the uninterning, this would just turn off all of yasnippet's modes if you type `M-x unload-feature yasnippet`?  That still sounds useful (Debian, at least, installs the default snippets without the `.yas-setup.el`).

**Comment by npostavs** [comment]
Hmm, actually I was wrong, `unload-feature` only covers major modes.

Okay, so `yasnippet-unload-feature` should disable `yas-minor-mode` in all buffers, undo `put` calls performed by `cl-defstruct` to avoid [Emacs bug#25088](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25088).

And `C-u M-x unload-feature yasnippet` will ignore the `require` done by `.yas-setup.el` and others.

**Comment by spwhitton** [comment]
Thanks!
