### ISSUE TITLE
warning / alias for `yas--snippets-at-point`

### ISSUE THREAD

**Issue by nverno** [joaotavora/yasnippet#754]
Should there be a an obsolete warning / alias for `yas--snippet-at-point` to `yas-active-snippets`?

**Comment by npostavs** [comment]
See also https://github.com/joaotavora/yasnippet/commit/2ca6321b47c7054a339adcf982f1e4723490404a#commitcomment-20032427

I was thinking no at first, because `yas--snippet-at-point` was supposed to be "internal", but it was actually being used in at least one other package, so perhaps we should consider it a de facto API.

**Comment by nverno** [comment]
I think it may be widespread, I know I use it in my own functions, but also see it in `auto-yasnippet`, which you may be referring to.

**Comment by npostavs** [comment]
I was referring to `company-coq`, so that makes at least 2 packages. Enough to justify aliasing this.
