### ISSUE TITLE
Tab expansion doesn't work in web-mode

### ISSUE THREAD

**Issue by deflexor** [joaotavora/yasnippet#772]
When i type `for` and then M-x yas-expand it works fine, but when i type `for` and hit `Tab` then nothing happens. If I open another file in another mode, `Tab` expansion works just fine.

**Comment by npostavs** [comment]
Can you reproduce this from [`emacs -Q`][emacs-Q]? I tried downloading [web-mode](https://github.com/fxbois/web-mode) and it worked for me (except there is no `for` snippet, but expanding `form` with `<tab>` works fine).

Emacs 24.5, latest `master` of web-mode (https://github.com/fxbois/web-mode/commit/2d05692634766cfa647d9441aaf7f8d95d2d5206), latest `master` of yasnippet (https://github.com/joaotavora/yasnippet/commit/e74f00e70324101130c00b10af15f1f23e150654).

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by deflexor** [comment]
I use Emacs 24.5, web-mode and yasnippet installed via emacs builtin `package-install`.

It seems I found the cause. If there is malformed html somewhere in the file, like: `<a href="/extra_quote_attr"">test</a>`, then anywhere after this malformed tag expansion doesn't work.

**Comment by npostavs** [comment]
I guess that's because of the default `yas-buffer-local-condition` which prevents expansion inside strings. Hmm, it looks `web-mode` fontlocks the string correctly, but it doesn't fix the actual syntax. I consider this a bug in `web-mode` (i.e., that `(nth 3 (syntax-ppss (point)))` returns non-nil with point following the bad tag), but you can set `yas-buffer-local-condition` to `t` to avoid this.

 http://joaotavora.github.io/yasnippet/snippet-expansion.html#sec-2-2
