### ISSUE TITLE
yas-choose-value always requires match

### ISSUE THREAD

**Issue by dakra** [joaotavora/yasnippet#934]
Not sure if this is really a bug.
I want a function like `yas-choose-value` (or option for it) where
the user can select from the strings I provided but also can specify his own.
So like setting `REQUIRE-MATCH` to nil when using `completing-read`.

`yas-choose-value` requires the user to always select one of the predefined values.

**Comment by npostavs** [comment]
> Not sure if this is really a bug.

It's a feature request.

This idea isn't really compatible with `yas-choose-value` since it lets the user choose the completion style; one of the possibilities is `yas-x-prompt`, which doesn't allow typing at all. Although sometimes I think I should just get rid of it.

I suppose adding something like `yas-completing-read` would be easy enough.
```elisp
(defun yas-completing-read (&rest args)
  (unless (or yas-moving-away-p
              yas-modified-p)
    (apply completing-read-function args)))
```

Maybe that should even replace `yas-choose-value` completely...

**Comment by joaotavora** [comment]
> Maybe that should even replace yas-choose-value completely...

Amen :)
