### ISSUE TITLE
Cannot create a replacement for old yas-with-comment command

### ISSUE THREAD

**Issue by averter** [joaotavora/yasnippet#946]
Hi,

I have spent a good couple of hours trying to find a way to replace this very simple snippet which does not work since my last emacs upgrade
```
# -*- mode: snippet -*-
# name: time stamp
# key: ts
# --
`(yas-with-comment " Time-stamp: <>")`

```
I am aware that the `yas-with-comment` command has been removed from yasnippet. I have looked on the documentation for alternative commands and other blogs online without any luck. So my question is how can I emulate the same behaviour as the above snippet? Many thanks in advance

**Comment by averter** [comment]
Almost. This code did the trick
```
# -*- mode: snippet -*-
# name: time stamp
# key: ts
# --
`(let ((start (point)))
        (insert " Time-stamp: <>")
  	(comment-region start (point)))`
```
Obrigado for the insight. Um abraço!

**Comment by npostavs** [comment]
> `yas-with-comment` command has been removed from yasnippet.

Technically, it was never part of yasnippet, it came with the yasnippet-snippets collection (ref #856). You can just add the old definition back into your own config if you like. Alternatively, use `comment-start` and `comment-end` as in AndreaCrotti/yasnippet-snippets#221:

```
`comment-start` Time-stamp: <>`comment-end`
```

> Almost. This code did the trick
> ```
> `(let ((start (point)))
>         (insert " Time-stamp: <>")
> ```
> 

Please don't use `insert` within a backquote expression, this is deprecated and not guaranteed to continue working in future yasnippet versions (notice that @joaotavora's suggestion uses a `#type command` snippet which puts the responsibility of insertion entirely onto whatever lisp code you write, so that is quite different).

**Comment by averter** [comment]
Thanks @npostavs . I prefer to use the stable, long-run implemented commands so I have switched to your suggestion. Cheers
